### ISSUE TITLE
README Improvements 

### ISSUE THREAD

**Issue by ijacobs-cpa** [mingming-ma/txt2html#1]
The included README.md could use the following improvements/additions:
- Include any details about commands that can be used in your program (ex -v,-h)
- Including examples of running the program. 
- installation instructions (Including how to clone from GitHub / check that Python is installed. etc.)
- include some more explanation on how to use the program including limits on what the program can do and any features it has.

Also in the example shown on how to run the program the name of the main file (text2html.py) is misspelled (should be txt2html.py)

**Comment by mingming-ma** [comment]
README Improvements in the commit [4d8fd71](https://github.com/mingming-ma/txt2html/commit/4d8fd71af8806475c7ebe840175602c55b6b24e4)
