### ISSUE TITLE
Version and help command flag improvements 

### ISSUE THREAD

**Issue by ijacobs-cpa** [mingming-ma/txt2html#2]
The version flag only prints out the version number, not the version number + name of the program as described in the release 0.1 notes. 

The help flag could use some more detail including some instructions on how to use the program (like how you display it in GitHub) and the other available command flags (-h, --help) and what they do.

**Comment by mingming-ma** [comment]
Fix this issue in commit [8f2adb5](https://github.com/mingming-ma/txt2html/commit/8f2adb5c818417122218cf2685c440b57b83ed59)
