### ISSUE TITLE
Optional Features added or planned

### ISSUE THREAD

**Issue by ijacobs-cpa** [mingming-ma/txt2html#3]
Optional features that were added in the code (title for HTML) have no explanation in the README as well as no explanation of features that are planned to be added to the program. 

Something that could be worked on however could be being able to run command flags with files at the same time (i.e. ./txt2html.py <file> -v) for future optional features.

**Comment by mingming-ma** [comment]
Add planned features in the commit [8b3f12d](https://github.com/mingming-ma/txt2html/commit/8b3f12d3803786132b28b19d98301c15a9181171)
