### ISSUE TITLE
Code Formatting and Documentation

### ISSUE THREAD

**Issue by ijacobs-cpa** [mingming-ma/txt2html#5]
Code formatting: 

Having non-function code around (above and below) your functions makes it a bit confusing to understand how the code flows. Maybe consider grouping the functions in one area and having the non-function code below (or above) the functions to stand out. Also maybe include a main() (non-issue) so that it looks more clearer to a user. 

Your code could also use a bit more documentation to explain what is happening at certain lines of code (For example in your process_txt_file() function adding more comments when opening a file for reading/writing)

**Comment by mingming-ma** [comment]
Fix this issue in this commit [0aaff97](https://github.com/mingming-ma/txt2html/commit/0aaff97c470047d5d4da5cfd83fca1104b993d46)
